module.exports = {
        originErrorText: 'Cannot delete starting position!',
        mapText: 'Click anywhere in the map to add a new point',
        originInputText: 'Enter an address for your starting location',
        originMarker: 'You can drag the starting location where you prefer',
        temporaryMarker: 'Click on the green marker for additional info',
        defaultMarker: 'Click on the marker to remove it',
        searchSuggestion: 'e.g. Grab a coffee',
        searchFor: 'Search for',
        searchText: 'Search places by keyword',
        goTo: 'Go to',
        errandText: 'Enter a new errand',
        pointOnMap: 'Point on the map',
        returnTo: 'Return to',
        currentLocation: 'Current location',
};
