---

- name: be sure environment variables are set
  template: src=environment.j2 dest=/etc/profile.d/environment.sh

- name: be sure nodejs is installed
  apt: name=nodejs update_cache=yes state=latest

- name: be sure node is configured to point to nodejs
  alternatives: name=node link=/usr/bin/node path=/usr/bin/nodejs

- name: be sure npm is installed
  apt: name=npm update_cache=yes state=latest

- name: be sure bower is installed
  npm: name=bower global=yes

- name: be sure jasmine is installed
  npm: name=jasmine-node global=yes

- name: be sure grunt is installed
  npm: name=grunt-cli global=yes

- name: be sure browserify is installed
  npm: name=browserify global=yes

- name: be sure forever is installed
  npm: name=forever global=yes
